name = "plate-marketplace-api"
main = "backend/hono.ts"
compatibility_date = "2024-01-01"
node_compat = true

[observability]
enabled = true

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "1aa88018164e4706905b964789217850"
preview_id = "c985bfb57b2942de9a204dc3df91121b"

[vars]
ENVIRONMENT = "production"

[env.production]
name = "plate-marketplace-api"

[env.staging]
name = "plate-marketplace-api-staging"
